site_name: SIPNET Documentation

nav:
  - Home: README.md
  - Model Description:
    - Parameters: parameters.md
    - Model Specification: model-structure.md
  - User Guide:
      - Getting Started: user-guide/getting-started.md
      - Running SIPNET: user-guide/running-sipnet.md
      - Model Inputs: user-guide/model-inputs.md
      - Model Outputs: user-guide/model-outputs.md
  - Developer Guide:
      - Code Structure: developer-guide/code-structure.md
      - Adding New Command Line Options: developer-guide/cli-options.md
      - Logging: developer-guide/logging.md
      - Testing: developer-guide/testing.md
  - Contributing: CONTRIBUTING.md
  - API Reference: api/index.html
  - Releases: https://github.com/PecanProject/sipnet/releases
  - Changelog: CHANGELOG.md
  - Code of Conduct: CODE_OF_CONDUCT.md

theme:
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - navigation.expand
  icon:
    edit: material/pencil
  palette:
    - scheme: default
      primary: green
      accent: light green

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - pymdownx.superfences



extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  arithmatex:
    inline_syntax: ['\\(', '\\)']
    block_syntax: ['\\[', '\\]']

repo_url: https://github.com/PecanProject/sipnet
edit_uri: edit/master/docs/

# Use relative URLs so previews under subpaths work
use_directory_urls: true
# Avoid absolute site_url; let MkDocs generate relative asset paths
site_url: ""
